### ISSUE TITLE
Crash when using The Aether Reborn

### ISSUE THREAD

**Issue by AlisterGontineac** [Draylar/identity#291] opened 2021-09-22 21:17 UTC
**Bug description**
*Tried to open the identity menu in creative. Game crashed after opening the menu when using The Aether Reborn( https://www.curseforge.com/minecraft/mc-mods/aether-reborn ). I think there is incompatibility with an entity from that mod*

**Game log:**
*https://paste.ee/p/RPJoa.*

**Comment by James103** [comment] 2021-09-22 23:12
Duplicate of #277

**Comment by Draylar** [comment] 2021-10-06 02:17
Hoping to have this ""fixed"" (no longer hard crashes) in 1.15.0 beta. I'm going to keep #277 open in hopes of solving the actual problem in the future. Thanks for the report.

**Closed as completed** 2021-10-06 02:23 UTC
Labels: bug
