### ISSUE TITLE
game crash when morph menu is opened in creative

### ISSUE THREAD

**Issue by tatu141** [Draylar/identity#226] opened 2021-06-03 10:35 UTC
i have some mods n the morph crashes the game when used in creative, survival works just fine     
 https://pastebin.com/aZ0u3MdA

**Comment by adroslice** [comment] 2021-09-23 16:08
Possibly duplicate of #277

**Comment by Draylar** [comment] 2021-10-10 01:41
72a087a0d will fix this from crashing your game completely. The problem is that some mobs assume they aren't being rendered in a GUI (or something like that); going into creative mode, which shows all entities, is the perfect way to trigger the issue.

**Closed as completed by Draylar** 2021-10-10 01:41 UTC
Labels: bug
