### ISSUE TITLE
Game crashes when try use the mod

### ISSUE THREAD

**Issue by Aaron13381** [Draylar/identity#41] opened 2020-10-02 13:05 UTC
The Game crashes right when I press the button to see what I can morph into

**Comment by James103** [comment] 2020-10-02 13:08
Are you able to reproduce the crash? If so, can you provide the crash report and logs?

**Comment by Aaron13381** [comment] 2020-10-04 22:29
Yes. Link to crash report [https://pastebin.com/18dPZ7we]

**Comment by James103** [comment] 2020-10-04 22:38
Based on the crash report, it's probably related to / a duplicate of #40 (Spinnery mentioned, MC 1.16.3).

**Comment by Draylar** [comment] 2020-10-05 18:23
yes, this mod only supports 1.16.1, not on .2 or .3 yet

**Comment by Draylar** [comment] 2020-10-26 15:21
Should be fixed in 1.9.1 for 1.16.2/1.16.3, lmk if anything breaks :)

**Closed as completed by Draylar** 2020-10-26 15:21 UTC

**Comment by ImortisInglorian** [comment] 2020-11-13 23:50
[crash-2020-11-13_18.40.35-client.txt](https://github.com/Draylar/identity/files/5539788/crash-2020-11-13_18.40.35-client.txt)
I am getting a crash too, but instead of the spinnery mod error in the above logs, I get a duplicate ID error.  Is it possible that this is conflicting with another mod in my  pack and if so, what is the best way to determine which one?

**Comment by Draylar** [comment] 2020-11-14 00:39
Your crash seems to be from Ladysnake's BLAST mod. I found an issue related to this on their repo [here](https://github.com/Ladysnake/BLAST/issues/6).

Identity triggers the crash because it creates a new instance of every entity in the game and renders them when you open the swap menu for the first time.

**Comment by ImortisInglorian** [comment] 2020-11-14 00:46
I noticed that mod was mentioned there.  Sorry for not thinking to look into it.  Thanks for your help!
