### ISSUE TITLE
game Crash when another player turns into some mobs. zombie. potentially spider or squid too.

### ISSUE THREAD

**Issue by realflow100** [Draylar/identity#65] opened 2020-11-21 08:42 UTC
game Crash when another player turns into some mobs. zombie. potentially spider or squid too.

using identity-1.10.0-beta-1.16.3 version

minecraft 1.16.4

**Comment by James103** [comment] 2020-11-21 13:36
1. Are you able to reproduce this crash?
2. Do you have the crash report and/or log? If so, can you please post them here?

**Comment by realflow100** [comment] 2020-11-22 12:03
it happens every time
it only crashes the OTHER person. not the person changing morph but the other person
so my friend would change into a zombie and MY GAME would crash. not his.
Some sort of rendering entity error
[crash-2020-11-21_03.39.12-client.txt](https://github.com/Draylar/identity/files/5579428/crash-2020-11-21_03.39.12-client.txt)

also latest log showing alot of failed to play sounds. i think its also another issue.
I deleted some of our chat messages for privacy reasons though.
[latest.log](https://github.com/Draylar/identity/files/5579434/latest.log)

**Comment by Draylar** [comment] 2020-11-27 22:07
This should be fixed in the next release (I know what the issue is, but can't reproduce it easily, so I'm hoping my fix works). Let me know if it pops up again.

**Closed as completed by Draylar** 2020-11-27 22:07 UTC
