### ISSUE TITLE
Only red fox available in menu, and foxes still run from fox disguise.

### ISSUE THREAD

**Issue by KupferudelWolf** [Draylar/identity#79] opened 2020-12-15 06:34 UTC
As the title says. Killing a white fox adds a red fox to the menu, and when you're disguised as a fox, foxes still run from you (unless you crouch, of course). Is this intentional? Is this planned to change?

**Comment by realflow100** [comment] 2020-12-15 19:19
I'm taking a wild guess and thinking its a planned feature at some point. probably being worked on even.

**Comment by Draylar** [comment] 2020-12-15 19:39
The problem is that theme "types," are handled differently for every entity. For example, `FoxEntity` has `FoxEntity.Type` (which is either `RED` or `SNOW`, while `SlimeEntity` has an integer representing size.  I don't have a way to abstract this down yet, which is why you can only use whatever the entity defaults to at the moment.

Foxes running from players with a fox identity has been fixed in the latest update.

Redirecting to #55 for the sub-typing issue.

**Closed as completed by Draylar** 2020-12-15 19:39 UTC
