### ISSUE TITLE
Game doesn't load sometimes, and even crashes sometimes.

### ISSUE THREAD

**Issue by JoseBlackYT** [Draylar/identity#198] opened 2021-05-04 00:21 UTC
**Bug description**
*My game does load(sometimes), but when i click on new world it either just crashes, or when it doesn't and I create a new world, it simply stops at 0% or 1%. I don't have any other mods other than identity and optifine, and in other versions optifine didn't seem to cause any issues.*

**Game log:**
*No game log, just Exit Code 0..*

**Note:**
*I tried doing it with Sodium and it just crashed with Exit Code 0, again.*

**Comment by James103** [comment] 2021-05-04 00:26
Duplicate of #197

**Comment by JoseBlackYT** [comment] 2021-05-04 00:35
I opened that lmao, i just wanted to add the bug label

**Comment by Draylar** [comment] 2021-05-04 02:43
if you are on fabric api 34: downgrade fabric api to <=33 or upgrade CCA manually until I update the dependency
if not: get rid of optifine and try again

**Comment by JoseBlackYT** [comment] 2021-05-04 11:33
Worked like a charm! Thanks. I really just needed to downgrade fabric api to 33, ty.

**Closed as completed** 2021-05-04 11:34 UTC
Labels: bug
