### ISSUE TITLE
Can't become an arctic fox

### ISSUE THREAD

**Issue by Zunkz** [Draylar/identity#227] opened 2021-06-07 22:27 UTC
That's literally it I can't become one there isn't an option

**Comment by James103** [comment] 2021-06-17 18:25
Likely a duplicate of #55

**Comment by Foxite** [comment] 2022-05-25 15:40
I'm looking into this but it seems to require a major intervention into the code, as identities/abilities are stored by the class of the entity, and arctic foxes and red foxes are the same class.

This has also prevented me from adding a fox ability that is different depending on the fox type, so I'm considering this a high priority task on my personal schedule :grin:

**Comment by Draylar** [comment] 2022-05-27 20:34
Done in 2.3.0!

**Closed as completed by Draylar** 2022-05-27 20:34 UTC
Labels: bug
